spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/sample-db
    username: db_user
    password: db_pass
  platform: mysql
  driverClassName: com.mysql.jdbc.Driver
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
#  main:
#    lazyInitialization: true
management:
  endpoints:
    web:
      exposure:
        include: health

#logging:
#  level:
#    org:
#      springframework:
#        boot:
#          autoconfigure: DEBUG